version: '3'

tasks:
  run:
    cmds:
      - echo 'FM-BOT DEV MODE :'
      - go run cmd/main.go
  genvec:
    cmds:
      - echo 'Generating Vectores from PDF'
      - go run scripts/genvecs.go
    silent: true